# Generated by Django 3.2 on 2021-04-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('publisher', models.TextField()),
                ('callnumber', models.CharField(max_length=100)),
                ('ISBN', models.IntegerField()),
                ('picturename', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('student_id', models.IntegerField()),
                ('ISBN', models.IntegerField()),
                ('mothod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('typeof', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.IntegerField()),
                ('text', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trips.test')),
            ],
        ),
    ]
