# Generated by Django 3.2 on 2021-04-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='typeof',
        ),
        migrations.CreateModel(
            name='TypeOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trips.choice')),
            ],
        ),
    ]
