# Generated by Django 3.2 on 2021-04-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20210408_0228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeOF',
            new_name='Type',
        ),
    ]
