# Generated by Django 3.2 on 2021-04-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_rename_typeof_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='pointrecord',
            old_name='student_id',
            new_name='student',
        ),
    ]
