# Generated by Django 3.2 on 2021-04-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20210408_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointrecord',
            old_name='student',
            new_name='studentID',
        ),
    ]
