# Generated by Django 3.2 on 2021-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_remove_pointrecord_mothod'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
