# Generated by Django 3.2 on 2021-04-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_booklist_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='ISBN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='callnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='picturename',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trips.test'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='ISBN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='studentID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trips.choice'),
        ),
        migrations.AlterField(
            model_name='type',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
