# Generated by Django 3.2 on 2021-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='picturename',
            field=models.ImageField(blank=True, null=True, upload_to='bookcover'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
    ]
