# Generated by Django 3.2 on 2021-04-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_file_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='booklist',
            name='typeof',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
