# Generated by Django 3.2 on 2021-04-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_auto_20210414_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trips.test', verbose_name='問題'),
        ),
    ]
