# Generated by Django 3.2 on 2021-04-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_auto_20210418_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='author',
            field=models.TextField(blank=True, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='callnumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='索書號'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='館藏地'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='picturename',
            field=models.ImageField(blank=True, null=True, upload_to='bookcover', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='publisher',
            field=models.TextField(blank=True, null=True, verbose_name='出版者'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='題名'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='typeof',
            field=models.IntegerField(blank=True, null=True, verbose_name='類型'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='選項編號'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='選項文字'),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='ISBN',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='pointrecord',
            name='studentID',
            field=models.IntegerField(blank=True, null=True, verbose_name='學號'),
        ),
        migrations.AlterField(
            model_name='type',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trips.choice', verbose_name='屬於的選項'),
        ),
        migrations.AlterField(
            model_name='type',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='類型'),
        ),
    ]
