# Generated by Django 3.2 on 2021-04-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_auto_20210418_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon', verbose_name='圖片')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
            ],
        ),
    ]
