# Generated by Django 3.2 on 2021-04-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='share_img', verbose_name='圖片')),
            ],
        ),
        migrations.AddField(
            model_name='booklist',
            name='share_img',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.RESTRICT, to='trips.choice', verbose_name='分享預覽圖'),
            preserve_default=False,
        ),
    ]
