# Generated by Django 3.2 on 2021-04-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_auto_20210429_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='share_img',
        ),
    ]
