# Generated by Django 3.2 on 2021-04-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_remove_booklist_share_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='share_img',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.RESTRICT, to='trips.choice', verbose_name='分享預覽圖'),
            preserve_default=False,
        ),
    ]
