# Generated by Django 3.2 on 2021-04-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_booklist_share_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='share_img',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trips.choice', verbose_name='分享預覽圖'),
        ),
    ]
