# Generated by Django 3.2 on 2021-04-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_alter_shareimg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='share_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trips.choice', verbose_name='分享預覽圖'),
        ),
        migrations.AlterField(
            model_name='shareimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='share_img', verbose_name='圖片'),
        ),
    ]
