# Generated by Django 3.2 on 2021-04-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_auto_20210429_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='share_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trips.shareimg', verbose_name='分享預覽圖'),
        ),
    ]
