# Generated by Django 3.2 on 2021-04-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_alter_booklist_share_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imf', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='圖片')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
            ],
        ),
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
