# Generated by Django 3.2 on 2021-04-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_auto_20210430_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='imf',
            new_name='img',
        ),
    ]
