# Generated by Django 3.2 on 2021-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0027_alter_pointrecord_typeof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('studentID', models.IntegerField(blank=True, null=True, verbose_name='學號')),
                ('text', models.TextField(blank=True, null=True, verbose_name='推薦內容')),
            ],
        ),
    ]
