# Generated by Django 3.2 on 2021-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0028_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='typeof',
            field=models.IntegerField(blank=True, null=True, verbose_name='類型'),
        ),
    ]
